version: '3.5'

services:

  zipkin:
    image: ghcr.io/openzipkin/zipkin:2.23
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411 #Zipkin UI and HTTP Api
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616" # jms
      - "8161:8161"   # web

  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:3.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper