server:
  port: 9093
spring:
  application:
    name: appC
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web
  sleuth:
    baggage:
      remoteFields:
        - country-code
      tagFields:
        - country-code
      correlation-fields:
        - country-code
  mvc:
    log-request-details: true
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org:
      springframework:
        web: TRACE
