server:
  port: 9098
spring:
  application:
    name: appH
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web
  mvc:
    log-request-details: true
logging:
  level:
    org:
      springframework:
        web: TRACE
